//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        public int PID { get; set; }


        [Display(Name = "Product Name")]
        [Required(ErrorMessage = "Name is required.")]
        public string Pname { get; set; }

        [Display(Name = "Category")]
        [Required(ErrorMessage = "Product Category is required.")]
        public string Pcategory { get; set; }

        [Display(Name = "Price")]
        [Required(ErrorMessage = "Price is required.")]
        public double Pprice { get; set; }

        [Display(Name = "Stock")]
        [Required(ErrorMessage = "Stock is required.")]
        public int Pstock { get; set; }

        [Display(Name = "Supplier")]
        [Required(ErrorMessage = "Supplier is required.")]
        public string Supplier { get; set; }

        [Display(Name = "DOM")]
        [Required(ErrorMessage = "Man Date is required.")]
        public System.DateTime Mfdate { get; set; }

        [Display(Name = "Exp Date")]
        [Required(ErrorMessage = "Ex Date is required.")]
        public System.DateTime Expdate { get; set; }
    }
}
