//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bookstbl
    {
        public int BID { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessage = "The book title is required.")]
        public string BTitle { get; set; }

        [Display(Name = "Author")]
        [Required(ErrorMessage = "Author is required.")]
        public string Author { get; set; }

        [Display(Name = "Category")]
        [Required(ErrorMessage = "Book Category is required.")]
        public string Category { get; set; }

        [Display(Name = "Price")]
        [Required(ErrorMessage = "Price is required.")]
        public double Price { get; set; }

        [Display(Name = "Available Copies")]
        [Required(ErrorMessage = "Copies are required.")]
        public int Copies { get; set; }

        [Display(Name = "Publisher")]
        [Required(ErrorMessage = "Publisher is required.")]
        public string Publisher { get; set; }

        [Display(Name = "Publish Date")]
        [Required(ErrorMessage = "Publication date is required.")]
        public string PublishDate { get; set; }
    }
}
