//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ass_4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int vid { get; set; }
        public double price { get; set; }
        public int stock { get; set; }
        public int yom { get; set; }
        public string vname { get; set; }
        public string category { get; set; }
        public string brand { get; set; }
        public string condition { get; set; }
        public string supplier { get; set; }
    }
}
